import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useOrg } from '../context/OrgContext';
import { useAuth } from '../context/AuthContext';

const SECTORS = [
  'Energy', 'Water', 'Transport', 'Health', 'Communications',
  'Banking & Finance', 'Defence', 'Education', 'Government', 'Other',
];

/**
 * Shown after login when the user has no org yet.
 * Two paths: create a new org, or join an existing one via invite code.
 * Invite code format: "{orgId}:{inviteId}" — generated by OrgSettings when inviting a member.
 */
export default function OrgOnboarding() {
  const { createOrg, acceptInvite } = useOrg();
  const { logout } = useAuth();

  const [tab, setTab] = useState('create'); // 'create' | 'join'
  const [name, setName]     = useState('');
  const [sector, setSector] = useState('');
  const [code, setCode]     = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError]   = useState('');

  // Auto-switch to join tab if a pending invite was stored during registration
  useEffect(() => {
    const pending = sessionStorage.getItem('pending_invite');
    if (pending) {
      setCode(pending);
      setTab('join');
    }
  }, []);

  async function handleCreate(e) {
    e.preventDefault();
    if (!name.trim()) { setError('Organisation name is required'); return; }
    setIsLoading(true);
    setError('');
    try {
      await createOrg({ name: name.trim(), sector });
    } catch (err) {
      setError(err.message || 'Failed to create organisation');
    } finally {
      setIsLoading(false);
    }
  }

  async function handleJoin(e) {
    e.preventDefault();
    const parts = code.trim().split(':');
    if (parts.length !== 2 || !parts[0] || !parts[1]) {
      setError('Invalid invite code. Expected format: orgId:inviteId');
      return;
    }
    const [orgId, inviteId] = parts;
    setIsLoading(true);
    setError('');
    try {
      await acceptInvite(inviteId, orgId);
      sessionStorage.removeItem('pending_invite');
      // OrgContext onSnapshot will update currentOrg → OrgGate unmounts this screen
    } catch (err) {
      setError(err.message || 'Failed to join organisation');
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white rounded-2xl shadow-xl p-8 w-full max-w-md"
      >
        {/* Logo / brand */}
        <div className="text-center mb-6">
          <div className="w-14 h-14 bg-blue-600 rounded-xl flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
            </svg>
          </div>
          <h1 className="text-2xl font-bold text-gray-900">Set up your workspace</h1>
          <p className="text-gray-500 mt-1 text-sm">
            Create a new organisation or join an existing one.
          </p>
        </div>

        {/* Tab switcher */}
        <div className="flex rounded-xl p-0.5 mb-6 bg-gray-100">
          {[
            { key: 'create', label: 'Create Organisation' },
            { key: 'join',   label: 'Join with Invite Code' },
          ].map(({ key, label }) => (
            <button
              key={key}
              type="button"
              onClick={() => { setTab(key); setError(''); }}
              className={`flex-1 py-2 rounded-[10px] text-xs font-semibold transition-all ${
                tab === key
                  ? 'bg-white text-gray-900 shadow-sm'
                  : 'text-gray-500 hover:text-gray-700'
              }`}
            >
              {label}
            </button>
          ))}
        </div>

        {tab === 'create' ? (
          <form onSubmit={handleCreate} className="space-y-5">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Organisation name <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                value={name}
                onChange={e => setName(e.target.value)}
                placeholder="Acme Corp"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none text-sm"
                autoFocus
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Sector <span className="text-gray-400 font-normal">(optional)</span>
              </label>
              <select
                value={sector}
                onChange={e => setSector(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none text-sm bg-white"
              >
                <option value="">Select sector…</option>
                {SECTORS.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
            </div>

            {error && (
              <p className="text-sm text-red-600 bg-red-50 rounded-lg px-3 py-2">{error}</p>
            )}

            <button
              type="submit"
              disabled={isLoading}
              className="w-full bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white font-semibold py-2.5 rounded-lg transition-colors text-sm"
            >
              {isLoading ? 'Creating…' : 'Create organisation'}
            </button>
          </form>
        ) : (
          <form onSubmit={handleJoin} className="space-y-5">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Invite Code <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                value={code}
                onChange={e => setCode(e.target.value)}
                placeholder="Paste invite code from your team admin"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none text-sm font-mono"
                autoFocus
              />
              <p className="text-xs text-gray-400 mt-1">
                Ask your organisation admin for the invite code from Org Settings.
              </p>
            </div>

            {error && (
              <p className="text-sm text-red-600 bg-red-50 rounded-lg px-3 py-2">{error}</p>
            )}

            <button
              type="submit"
              disabled={isLoading}
              className="w-full bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white font-semibold py-2.5 rounded-lg transition-colors text-sm"
            >
              {isLoading ? 'Joining…' : 'Join organisation'}
            </button>
          </form>
        )}

        <div className="mt-6 text-center">
          <button
            onClick={logout}
            className="text-xs text-gray-400 hover:text-gray-600 transition-colors"
          >
            Sign out
          </button>
        </div>
      </motion.div>
    </div>
  );
}
